title: Dr. Developer Portfolio
email: your-email@example.com
description: >-
  Physician-Developer specializing in AI, computer vision, and LLMs for healthcare applications.
  Bridging the gap between medicine and technology.

# Site settings
baseurl: ""  # for local development
# url: "http://localhost:4000"  # for local development

# Production settings (uncomment and update these when deploying)
# baseurl: "/medical-ai-portfolio"  # your repository name
url: "https://narimannr2x.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages settings
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: null
gfm_quirks: paragraph_end

# Theme settings
theme_settings:
  # Colors
  primary_color: "#FFB366"
  text_color: "#333333"
  background_color: "#FFFFFF"

# Navigation
navigation:
  - title: Projects
    url: /#projects
  - title: Blog
    url: /#blog
  - title: Journey
    url: /#journey
  - title: Contact
    url: /#contact

# Collections
collections:
  projects:
    output: true
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
